import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ErrorCode, SeekPage } from '@inboxfm-connect/core-utils'
import {
    AppConnectionWithoutSensitiveData,
    CreateConnectSessionRequest,
    CreateConnectSessionResponse,
    ExecuteRequestBody,
    ListAppConnectionsRequestQuery,
} from '@inboxfm-connect/shared'
import { compile } from 'json-schema-to-typescript'
import { z } from 'zod'

const GENERATED_DIR = join(__dirname, '../src/generated')
const HEADER = '// AUTO-GENERATED by `npm run generate` in packages/connect-sdk — do not edit by hand.\n// Source of truth: Zod schemas in @inboxfm-connect/shared and @inboxfm-connect/core-utils.\n\n'

async function main(): Promise<void> {
    const checkOnly = process.argv.includes('--check')

    const contracts: Array<{ fileName: string, typeScript: string }> = await Promise.all([
        generateContract({ fileName: 'connect-session', schema: CreateConnectSessionRequest, typeName: 'CreateConnectSessionRequestContract' }),
        generateContract({ fileName: 'connect-session', schema: CreateConnectSessionResponse, typeName: 'CreateConnectSessionResponseContract', append: true }),
        generateContract({ fileName: 'connections', schema: ListAppConnectionsRequestQuery, typeName: 'ListConnectionsQueryContract' }),
        generateContract({ fileName: 'connections', schema: AppConnectionWithoutSensitiveData, typeName: 'ConnectionContract', append: true }),
        generateContract({ fileName: 'connections', schema: SeekPage(AppConnectionWithoutSensitiveData), typeName: 'ConnectionsPageContract', append: true }),
        generateContract({ fileName: 'execute', schema: ExecuteRequestBody, typeName: 'ExecuteRequestContract' }),
    ]).then(mergeByFileName)

    const errorCodeContract = generateErrorCodeContract()

    const allFiles = [...contracts, errorCodeContract]

    if (checkOnly) {
        checkNoDrift({ files: allFiles })
        return
    }

    mkdirSync(GENERATED_DIR, { recursive: true })
    for (const file of allFiles) {
        writeFileSync(join(GENERATED_DIR, `${file.fileName}.ts`), file.typeScript)
    }
    // eslint-disable-next-line no-console
    console.log(`Generated ${allFiles.length} file(s) in ${GENERATED_DIR}`)
}

async function generateContract({ fileName, schema, typeName, append }: GenerateContractOptions): Promise<{ fileName: string, typeScript: string }> {
    const jsonSchema = z.toJSONSchema(schema, { target: 'draft-7' })
    const typeScript = await compile(jsonSchema as Parameters<typeof compile>[0], typeName, {
        bannerComment: '',
        additionalProperties: false,
        style: { semi: false, singleQuote: true },
    })
    return { fileName, typeScript: append ? typeScript : HEADER + typeScript }
}

function mergeByFileName(entries: Array<{ fileName: string, typeScript: string }>): Array<{ fileName: string, typeScript: string }> {
    const byFileName = new Map<string, string>()
    for (const entry of entries) {
        const existing = byFileName.get(entry.fileName)
        byFileName.set(entry.fileName, existing ? `${existing}\n${entry.typeScript}` : entry.typeScript)
    }
    return Array.from(byFileName.entries()).map(([fileName, typeScript]) => ({ fileName, typeScript }))
}

function generateErrorCodeContract(): { fileName: string, typeScript: string } {
    const codes = Object.values(ErrorCode).sort()
    const union = codes.map((code) => `    | '${code}'`).join('\n')
    const typeScript = `${HEADER}export type ServerErrorCodeContract =\n${union}\n`
    return { fileName: 'error-code', typeScript }
}

function checkNoDrift({ files }: { files: Array<{ fileName: string, typeScript: string }> }): void {
    const drifted: string[] = []
    for (const file of files) {
        const existingPath = join(GENERATED_DIR, `${file.fileName}.ts`)
        const existing = readSafely({ path: existingPath })
        if (existing !== file.typeScript) {
            drifted.push(file.fileName)
        }
    }
    if (drifted.length > 0) {
        // eslint-disable-next-line no-console
        console.error(`Generated SDK types are out of date: ${drifted.join(', ')}.ts\nRun "npm run generate --workspace=@inboxfm-connect/sdk" and commit the result.`)
        process.exit(1)
    }
    // eslint-disable-next-line no-console
    console.log('Generated SDK types are up to date.')
}

function readSafely({ path }: { path: string }): string | undefined {
    try {
        return readFileSync(path, 'utf8')
    }
    catch {
        return undefined
    }
}

main().catch((error: unknown) => {
    // eslint-disable-next-line no-console
    console.error(error)
    process.exit(1)
})

type GenerateContractOptions = {
    fileName: string
    schema: z.core.$ZodType
    typeName: string
    append?: boolean
}
