import { MigrationInterface, QueryRunner } from 'typeorm'
import { system } from '../../../helper/system/system'
import { AppSystemProp } from '../../../helper/system/system-props'
import { DatabaseType } from '../../database-type'

const databaseType = system.get(AppSystemProp.DB_TYPE)

export class InitialSchema1700000000000 implements MigrationInterface {
    name = 'InitialSchema1700000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // "integration_metadata" below sorts piece versions with this custom collation
        // (natural/numeric ordering, e.g. "2.0.0" > "10.0.0" would sort wrong under plain
        // text collation) — PGlite doesn't support custom ICU collations, so this is
        // skipped there, matching the original piece-metadata migration's guard.
        if (databaseType !== DatabaseType.PGLITE) {
            await queryRunner.query('CREATE COLLATION en_natural (LOCALE = \'en-US-u-kn-true\', PROVIDER = \'icu\')')
        }
        await queryRunner.query('CREATE TABLE "execution" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "projectId" character varying(21) NOT NULL, "platformId" character varying(21) NOT NULL, "userId" character varying(21), "status" character varying NOT NULL, "prompt" character varying NOT NULL, "metadata" json NOT NULL, "tokenUsage" json, "cost" numeric, "finishTime" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cc6684fedf29ec4c86db8448a2b" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_execution_project_id" ON "execution" ("projectId") ')
        await queryRunner.query('CREATE INDEX "idx_execution_platform_id" ON "execution" ("platformId") ')
        await queryRunner.query('CREATE INDEX "idx_execution_status" ON "execution" ("status") ')
        await queryRunner.query('CREATE INDEX "idx_execution_created" ON "execution" ("created") ')
        await queryRunner.query('CREATE TABLE "tool_call" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "executionId" character varying(21) NOT NULL, "projectId" character varying(21) NOT NULL, "pieceName" character varying NOT NULL, "pieceVersion" character varying NOT NULL, "actionName" character varying NOT NULL, "connectionId" character varying(21), "input" json NOT NULL, "output" json, "status" character varying NOT NULL, "error" json, "latencyMs" numeric, "finished" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b07785c30d03ceb5a01ab47810c" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_tool_call_execution_id" ON "tool_call" ("executionId") ')
        await queryRunner.query('CREATE INDEX "idx_tool_call_project_id" ON "tool_call" ("projectId") ')
        await queryRunner.query('CREATE INDEX "idx_tool_call_created" ON "tool_call" ("created") ')
        await queryRunner.query('CREATE TABLE "trigger_binding" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "projectId" character varying(21) NOT NULL, "platformId" character varying(21) NOT NULL, "pieceName" character varying NOT NULL, "pieceVersion" character varying NOT NULL, "triggerName" character varying NOT NULL, "connectionId" character varying(21), "promptTemplate" character varying NOT NULL, "settings" json NOT NULL, "propertySettings" json, "status" character varying NOT NULL, CONSTRAINT "PK_c5468348e51537c98f5d3030a82" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_trigger_binding_project_id" ON "trigger_binding" ("projectId") ')
        await queryRunner.query('CREATE INDEX "idx_trigger_binding_platform_id" ON "trigger_binding" ("platformId") ')
        await queryRunner.query('CREATE INDEX "idx_trigger_binding_connection_id" ON "trigger_binding" ("connectionId") ')
        await queryRunner.query('CREATE INDEX "idx_trigger_binding_piece_trigger" ON "trigger_binding" ("pieceName", "triggerName") ')
        await queryRunner.query('CREATE TABLE "scheduled_task" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "projectId" character varying(21) NOT NULL, "platformId" character varying(21) NOT NULL, "prompt" character varying NOT NULL, "cronExpression" character varying NOT NULL, "timezone" character varying NOT NULL DEFAULT \'UTC\', "status" character varying NOT NULL, "lastRunAt" character varying, "nextRunAt" character varying, CONSTRAINT "PK_d690af24e57e30594c1948af1e6" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_scheduled_task_project_id" ON "scheduled_task" ("projectId") ')
        await queryRunner.query('CREATE INDEX "idx_scheduled_task_platform_id" ON "scheduled_task" ("platformId") ')
        await queryRunner.query('CREATE TABLE "file" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "projectId" character varying(21), "platformId" character varying(21), "data" bytea, "location" character varying NOT NULL, "fileName" character varying, "size" integer, "metadata" jsonb, "s3Key" character varying, "type" character varying NOT NULL DEFAULT \'UNKNOWN\', "compression" character varying NOT NULL DEFAULT \'NONE\', CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_file_project_id" ON "file" ("projectId") ')
        await queryRunner.query('CREATE INDEX "idx_file_type_created_desc" ON "file" ("type", "created") ')
        await queryRunner.query('CREATE TABLE "flag" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "value" jsonb NOT NULL, CONSTRAINT "PK_17b74257294fdfd221178a132d4" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE TABLE "project" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" TIMESTAMP WITH TIME ZONE, "ownerId" character varying(21) NOT NULL, "displayName" character varying NOT NULL, "type" character varying NOT NULL, "platformId" character varying(21) NOT NULL, "externalId" character varying, "maxConcurrentJobs" integer, "icon" jsonb NOT NULL, "releasesEnabled" boolean NOT NULL DEFAULT false, "metadata" jsonb, "poolId" character varying(21), "workerGroupId" character varying, CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_project_owner_id" ON "project" ("ownerId") ')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_project_platform_id_external_id" ON "project" ("platformId", "externalId") WHERE deleted IS NULL')
        await queryRunner.query('CREATE INDEX "idx_project_platform_id" ON "project" ("platformId") ')
        await queryRunner.query('CREATE INDEX "idx_project_pool_id" ON "project" ("poolId") ')
        await queryRunner.query('CREATE INDEX "idx_project_worker_group" ON "project" ("workerGroupId") ')
        await queryRunner.query('CREATE TABLE "store-entry" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "key" character varying(128) NOT NULL, "projectId" character varying(21) NOT NULL, "value" jsonb, CONSTRAINT "UQ_6f251cc141de0a8d84d7a4ac17d" UNIQUE ("projectId", "key"), CONSTRAINT "PK_afb44ca7c0b4606b19deb1680d6" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE TABLE "user" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "status" character varying NOT NULL, "platformRole" character varying NOT NULL, "identityId" character varying NOT NULL, "externalId" character varying, "platformId" character varying, "lastActiveDate" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_user_platform_id_email" ON "user" ("platformId", "identityId") ')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_user_platform_id_external_id" ON "user" ("platformId", "externalId") ')
        await queryRunner.query('CREATE INDEX "idx_user_identity_id" ON "user" ("identityId") ')
        await queryRunner.query('CREATE TABLE "app_connection" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "displayName" character varying NOT NULL, "externalId" character varying NOT NULL, "type" character varying NOT NULL, "status" character varying NOT NULL DEFAULT \'ACTIVE\', "platformId" character varying NOT NULL, "pieceName" character varying NOT NULL, "ownerId" character varying, "projectIds" character varying array NOT NULL, "scope" character varying NOT NULL, "value" jsonb NOT NULL, "metadata" jsonb, "pieceVersion" character varying NOT NULL, "preSelectForNewProjects" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_9efa2d6633ecc57cc5adeafa039" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_app_connection_platform_id_and_external_id" ON "app_connection" ("platformId", "externalId") ')
        await queryRunner.query('CREATE INDEX "idx_app_connection_owner_id" ON "app_connection" ("ownerId") ')
        await queryRunner.query(`CREATE TABLE "integration_metadata" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "authors" character varying array NOT NULL, "displayName" character varying NOT NULL, "logoUrl" character varying NOT NULL, "projectUsage" integer NOT NULL DEFAULT '0', "description" character varying, "platformId" character varying, "version" character varying ${databaseType !== DatabaseType.PGLITE ? 'COLLATE "en_natural" ' : ''}NOT NULL, "minimumSupportedRelease" character varying ${databaseType !== DatabaseType.PGLITE ? 'COLLATE "en_natural" ' : ''}NOT NULL, "maximumSupportedRelease" character varying ${databaseType !== DatabaseType.PGLITE ? 'COLLATE "en_natural" ' : ''}NOT NULL, "auth" json, "actions" json NOT NULL, "triggers" json NOT NULL, "pieceType" character varying NOT NULL, "categories" character varying array, "packageType" character varying NOT NULL, "archiveId" character varying(21), "i18n" json, CONSTRAINT "REL_b9f7d6d9b26ae4afe3c2f56e2e" UNIQUE ("archiveId"), CONSTRAINT "PK_a8fb05e0cd4597056771b89550d" PRIMARY KEY ("id"))`)
        await queryRunner.query('CREATE UNIQUE INDEX "idx_piece_metadata_name_platform_id_version" ON "integration_metadata" ("name", "version", "platformId") ')
        await queryRunner.query('CREATE TABLE "platform" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" character varying(21) NOT NULL, "name" character varying NOT NULL, "primaryColor" character varying NOT NULL, "themeColors" jsonb, "logoIconUrl" character varying NOT NULL, "fullLogoUrl" character varying NOT NULL, "favIconUrl" character varying NOT NULL, "cloudAuthEnabled" boolean NOT NULL DEFAULT true, "googleAuthEnabled" boolean NOT NULL DEFAULT true, "filteredPieceNames" character varying array NOT NULL, "filteredPieceBehavior" character varying NOT NULL, "allowedAuthDomains" character varying array NOT NULL, "allowedEmbedOrigins" character varying array NOT NULL DEFAULT \'{}\', "ssoDomain" character varying, "ssoDomainVerification" jsonb, "enforceAllowedAuthDomains" boolean NOT NULL, "emailAuthEnabled" boolean NOT NULL, "federatedAuthProviders" jsonb NOT NULL, "pinnedPieces" character varying array NOT NULL, "pieceSelectorConfig" jsonb, CONSTRAINT "REL_94d6fd6494f0322c6f0e099141" UNIQUE ("ownerId"), CONSTRAINT "PK_c33d6abeebd214bd2850bfd6b8e" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_platform_sso_domain" ON "platform" ("ssoDomain") WHERE "ssoDomain" IS NOT NULL')
        await queryRunner.query('CREATE TABLE "secret_manager_connection" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying(21) NOT NULL, "providerId" character varying NOT NULL, "name" character varying NOT NULL, "scope" character varying NOT NULL DEFAULT \'PLATFORM\', "projectIds" jsonb, "auth" jsonb, CONSTRAINT "PK_ceec5915638c59883b30e7c6cba" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_secret_manager_connection_platform_id" ON "secret_manager_connection" ("platformId") ')
        await queryRunner.query('CREATE TABLE "tag" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_0aaf8e30187e0b89ebc9c4764ba" UNIQUE ("platformId", "name"), CONSTRAINT "PK_8e4052373c579afc1471f526760" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE TABLE "piece_tag" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying NOT NULL, "pieceName" character varying NOT NULL, "tagId" character varying NOT NULL, CONSTRAINT "UQ_84a810ed305b758e07fa57f604a" UNIQUE ("tagId", "pieceName"), CONSTRAINT "PK_f06201adf8d82249e8f2f390426" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "tag_platformId" ON "piece_tag" ("platformId") ')
        await queryRunner.query('CREATE TABLE "user_invitation" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying NOT NULL, "type" character varying NOT NULL, "platformRole" character varying, "email" character varying NOT NULL, "projectId" character varying, "status" character varying NOT NULL, "projectRoleId" character varying, CONSTRAINT "PK_41026b90b70299ac5dc0183351a" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_user_invitation_email_platform_project" ON "user_invitation" ("email", "platformId", "projectId") ')
        await queryRunner.query('CREATE TABLE "ai_provider" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "config" json NOT NULL, "auth" json NOT NULL, "provider" character varying NOT NULL, "platformId" character varying(21) NOT NULL, "displayName" character varying NOT NULL, "enabledForChat" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_1046c2cb42f99614e1c7873744b" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_ai_provider_platform_id_provider" ON "ai_provider" ("platformId", "provider") ')
        await queryRunner.query('CREATE TABLE "ai_tool_config" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying(21) NOT NULL, "capability" character varying NOT NULL, "provider" character varying NOT NULL, "auth" json NOT NULL, "config" json, "enabled" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_c25f7b911a08ccd2f887d2bd07a" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_ai_tool_config_platform_capability" ON "ai_tool_config" ("platformId", "capability") ')
        await queryRunner.query('CREATE TABLE "project_role" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "permissions" character varying array NOT NULL, "platformId" character varying, "type" character varying NOT NULL, CONSTRAINT "PK_5974798305ac81d4a7d23ab1c6a" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE TABLE "table" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "folderId" character varying(21), "externalId" character varying NOT NULL, "trigger" character varying, "status" character varying, "projectId" character varying(21) NOT NULL, CONSTRAINT "PK_28914b55c485fc2d7a101b1b2a4" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_table_project_id_name" ON "table" ("projectId", "name") ')
        await queryRunner.query('CREATE INDEX "idx_table_folder_id" ON "table" ("folderId") ')
        await queryRunner.query('CREATE TABLE "field" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "type" character varying NOT NULL, "tableId" character varying(21) NOT NULL, "projectId" character varying(21) NOT NULL, "externalId" character varying NOT NULL, "data" jsonb, CONSTRAINT "PK_39379bba786d7a75226b358f81e" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_field_project_id_table_id_name" ON "field" ("projectId", "tableId", "name") ')
        await queryRunner.query('CREATE TABLE "record" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tableId" character varying(21) NOT NULL, "projectId" character varying(21) NOT NULL, CONSTRAINT "PK_5cb1f4d1aff275cf9001f4343b9" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_record_project_id_table_id" ON "record" ("projectId", "tableId") ')
        await queryRunner.query('CREATE INDEX "idx_record_table_id_project_id_record_id" ON "record" ("tableId", "projectId", "id") ')
        await queryRunner.query('CREATE TABLE "cell" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "recordId" character varying(21) NOT NULL, "fieldId" character varying(21) NOT NULL, "projectId" character varying(21) NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_6f34717c251843e5ca32fc1b2b8" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_cell_project_id_field_id_record_id_unique" ON "cell" ("projectId", "fieldId", "recordId") ')
        await queryRunner.query('CREATE TABLE "user_identity" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying NOT NULL, "password" character varying NOT NULL, "trackEvents" boolean, "newsLetter" boolean, "verified" boolean NOT NULL DEFAULT false, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "tokenVersion" character varying, "provider" character varying NOT NULL, "imageUrl" character varying, "lastLoggedInPlatformId" character varying(21), CONSTRAINT "UQ_7ad44f9fcbfc95e0a8436bbb029" UNIQUE ("email"), CONSTRAINT "PK_87b5856b206b5b77e6e2fa29508" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_user_identity_email" ON "user_identity" ("email") ')
        await queryRunner.query('CREATE TABLE "mcp_server" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying(21), "projectId" character varying(21), "type" character varying NOT NULL, "token" character varying NOT NULL, "disabledTools" jsonb, CONSTRAINT "PK_940f98ed91dd060f63e6fc5634e" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "mcp_server_project_id" ON "mcp_server" ("projectId") ')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_mcp_server_token" ON "mcp_server" ("token") ')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_mcp_server_platform_id" ON "mcp_server" ("platformId") ')
        await queryRunner.query('CREATE TABLE "mcp_oauth_client" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "clientId" character varying(64) NOT NULL, "clientSecret" character varying(128), "clientSecretExpiresAt" bigint NOT NULL DEFAULT \'0\', "clientIdIssuedAt" bigint NOT NULL, "redirectUris" character varying array NOT NULL, "clientName" character varying(255), "grantTypes" character varying array NOT NULL, "tokenEndpointAuthMethod" character varying(64) NOT NULL DEFAULT \'none\', CONSTRAINT "PK_779bfe67dd46793eaf526e1bc21" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_mcp_oauth_client_client_id" ON "mcp_oauth_client" ("clientId") ')
        await queryRunner.query('CREATE TABLE "mcp_oauth_authorization_code" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(128) NOT NULL, "clientId" character varying(64) NOT NULL, "userId" character varying(21) NOT NULL, "projectId" character varying(21), "platformId" character varying(21) NOT NULL, "redirectUri" character varying(2048) NOT NULL, "codeChallenge" character varying(256) NOT NULL, "codeChallengeMethod" character varying(8) NOT NULL DEFAULT \'S256\', "scopes" character varying array, "state" character varying(512), "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_bd8f45fa3a75c4fc0792eb0091a" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_mcp_oauth_code" ON "mcp_oauth_authorization_code" ("code") ')
        await queryRunner.query('CREATE TABLE "mcp_oauth_token" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "refreshToken" character varying(128) NOT NULL, "clientId" character varying(64) NOT NULL, "userId" character varying(21) NOT NULL, "projectId" character varying(21), "platformId" character varying(21) NOT NULL, "scopes" character varying array, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_45168e6e2a99c74779e45fab66b" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_mcp_oauth_token_refresh" ON "mcp_oauth_token" ("refreshToken") ')
        // pgvector is an optional extension (see AddToolSearchIndexTable1801000000000's original
        // comment) — managed/vanilla Postgres without it just runs tool-search on the keyword
        // floor, so table creation degrades gracefully instead of crash-looping the migration.
        const vectorAvailable = await queryRunner.query('SELECT EXISTS (SELECT 1 FROM pg_extension WHERE extname = \'vector\') AS available')
        if (vectorAvailable[0]?.available) {
            await queryRunner.query('CREATE TABLE "tool_search_index" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "objectKind" character varying NOT NULL, "pieceName" character varying NOT NULL, "pieceVersion" character varying NOT NULL, "objectName" character varying NOT NULL, "displayName" character varying NOT NULL, "retrievalDoc" text NOT NULL, "audience" character varying, "requiresConnection" boolean NOT NULL DEFAULT false, "categories" character varying array, "modelVersion" character varying NOT NULL, "embeddingInputHash" character varying NOT NULL, "embedding" vector, "platformId" character varying(21), CONSTRAINT "PK_cd208da2cdf1dc1d1ccb6830519" PRIMARY KEY ("id"))')
            await queryRunner.query('CREATE UNIQUE INDEX "uq_tsi_object_shared" ON "tool_search_index" ("pieceName", "objectKind", "objectName", "modelVersion") WHERE "platformId" IS NULL')
            await queryRunner.query('CREATE UNIQUE INDEX "uq_tsi_object_tenant" ON "tool_search_index" ("pieceName", "objectKind", "objectName", "platformId", "modelVersion") WHERE "platformId" IS NOT NULL')
            await queryRunner.query('CREATE INDEX "idx_tsi_filters" ON "tool_search_index" ("objectKind", "platformId", "audience", "requiresConnection") ')
        }
        await queryRunner.query('CREATE TABLE "connect_session" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "projectId" character varying(21) NOT NULL, "externalUserId" character varying NOT NULL, "allowedPieceNames" character varying array, "hashedToken" character varying NOT NULL, "truncatedToken" character varying NOT NULL, "expiresAt" character varying NOT NULL, "consumedAt" character varying, CONSTRAINT "PK_20a1b8eeea584538a80db5473e7" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_connect_session_project_id_external_user_id" ON "connect_session" ("projectId", "externalUserId") ')
        await queryRunner.query('CREATE INDEX "idx_connect_session_hashed_token" ON "connect_session" ("hashedToken") ')
        await queryRunner.query('CREATE TABLE "connect_api_key" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "displayName" character varying NOT NULL, "platformId" character varying(21) NOT NULL, "projectId" character varying(21) NOT NULL, "hashedValue" character varying NOT NULL, "truncatedValue" character varying NOT NULL, "lastUsedAt" character varying, CONSTRAINT "PK_9174e6ead7304f2e10b2416fc50" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_connect_api_key_project_id" ON "connect_api_key" ("projectId") ')
        await queryRunner.query('CREATE TABLE "connect_oauth_app" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying(21) NOT NULL, "pieceName" character varying NOT NULL, "clientId" character varying NOT NULL, "clientSecret" jsonb NOT NULL, CONSTRAINT "PK_0bd7d8eadddc6c015434139ce02" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_connect_oauth_app_platform_id_piece_name" ON "connect_oauth_app" ("platformId", "pieceName") ')
        await queryRunner.query('CREATE TABLE "concurrency_pool" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying(21) NOT NULL, "key" character varying NOT NULL, "maxConcurrentJobs" integer NOT NULL, CONSTRAINT "PK_8b6ddf189ac8d0971b198a5b1c2" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_concurrency_pool_platform_key" ON "concurrency_pool" ("platformId", "key") ')
        await queryRunner.query('CREATE TABLE "project_member" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "projectId" character varying(21) NOT NULL, "platformId" character varying(21) NOT NULL, "userId" character varying(21) NOT NULL, "projectRoleId" character varying(21) NOT NULL, CONSTRAINT "PK_64dba8e9dcf96ce383cfd19d6fb" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_project_member_project_id_user_id_platform_id" ON "project_member" ("projectId", "userId", "platformId") ')
        await queryRunner.query('CREATE TABLE "project_plan" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "projectId" character varying(21) NOT NULL, "name" character varying NOT NULL, "pieces" character varying array NOT NULL, "locked" boolean NOT NULL DEFAULT false, "piecesFilterType" character varying NOT NULL, CONSTRAINT "REL_4f52e89612966d95843e4158bb" UNIQUE ("projectId"), CONSTRAINT "PK_759d33fce71c95de832df935841" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_plan_project_id" ON "project_plan" ("projectId") ')
        await queryRunner.query('CREATE TABLE "signing_key" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "displayName" character varying NOT NULL, "platformId" character varying(21) NOT NULL, "publicKey" character varying NOT NULL, "algorithm" character varying NOT NULL, CONSTRAINT "PK_5cc161da020c79bb3ac9953edae" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE TABLE "oauth_app" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "pieceName" character varying NOT NULL, "platformId" character varying(21) NOT NULL, "clientId" character varying NOT NULL, "clientSecret" jsonb NOT NULL, CONSTRAINT "PK_3256b97c0a3ee2d67240805dca4" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_oauth_app_platformId_pieceName" ON "oauth_app" ("platformId", "pieceName") ')
        await queryRunner.query('CREATE TABLE "otp" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "type" character varying NOT NULL, "identityId" character varying(21) NOT NULL, "value" character varying NOT NULL, "state" character varying NOT NULL, CONSTRAINT "PK_32556d9d7b22031d7d0e1fd6723" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_otp_identity_id_type" ON "otp" ("identityId", "type") ')
        await queryRunner.query('CREATE TABLE "api_key" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "displayName" character varying NOT NULL, "platformId" character varying(21) NOT NULL, "hashedValue" character varying NOT NULL, "truncatedValue" character varying NOT NULL, "lastUsedAt" character varying, CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE TABLE "audit_event" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying NOT NULL, "projectId" character varying, "action" character varying NOT NULL, "userEmail" character varying, "projectDisplayName" character varying, "data" jsonb NOT NULL, "ip" character varying, "userId" character varying, CONSTRAINT "PK_481efbe8b0a403efe3f47a6528f" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "audit_event_platform_id_project_id_user_id_action_idx" ON "audit_event" ("platformId", "projectId", "userId", "action") ')
        await queryRunner.query('CREATE INDEX "audit_event_platform_id_user_id_action_idx" ON "audit_event" ("platformId", "userId", "action") ')
        await queryRunner.query('CREATE INDEX "audit_event_platform_id_action_idx" ON "audit_event" ("platformId", "action") ')
        await queryRunner.query('CREATE TABLE "platform_analytics_report" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying NOT NULL, "outdated" boolean NOT NULL, "cachedAt" TIMESTAMP NOT NULL, "runs" jsonb NOT NULL, "flows" jsonb NOT NULL, "users" jsonb NOT NULL, CONSTRAINT "PK_8b060dc8b2e5d9d91162ce2cc11" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_platform_analytics_report_platform_id" ON "platform_analytics_report" ("platformId") ')
        await queryRunner.query('CREATE TABLE "embed_subdomain" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying(21) NOT NULL, "hostname" character varying NOT NULL, "status" character varying NOT NULL, "cloudflareId" character varying NOT NULL, "verificationRecords" jsonb NOT NULL DEFAULT \'[]\', CONSTRAINT "PK_6070f7161f4c6960d2774dc9a86" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_embed_subdomain_platform_id" ON "embed_subdomain" ("platformId") ')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_embed_subdomain_hostname" ON "embed_subdomain" ("hostname") ')
        await queryRunner.query('CREATE TABLE "appsumo" ("uuid" character varying NOT NULL, "plan_id" character varying NOT NULL, "activation_email" character varying NOT NULL, CONSTRAINT "PK_3589df5be2973351814f727ae86" PRIMARY KEY ("uuid"))')
        await queryRunner.query('CREATE TABLE "connection_key" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "projectId" character varying(21) NOT NULL, "settings" jsonb NOT NULL, CONSTRAINT "PK_4dcf1d9ae4ba5eb261a6c775ad2" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_connection_key_project_id" ON "connection_key" ("projectId") ')
        await queryRunner.query('CREATE TABLE "app_credential" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "appName" character varying NOT NULL, "projectId" character varying(21) NOT NULL, "settings" jsonb NOT NULL, CONSTRAINT "PK_62eb102bb75a05d2951796a3b46" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE TABLE "platform_plan" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying(21) NOT NULL, "plan" character varying, "includedAiCredits" integer NOT NULL, "aiCreditsAutoTopUpCreditsToAdd" integer, "lastFreeAiCreditsRenewalDate" TIMESTAMP WITH TIME ZONE, "maxAutoTopUpCreditsMonthly" integer, "aiCreditsAutoTopUpThreshold" integer, "aiCreditsAutoTopUpState" character varying NOT NULL, "stripeSubscriptionStartDate" integer, "stripeSubscriptionEndDate" integer, "stripeSubscriptionCancelDate" integer, "environmentsEnabled" boolean NOT NULL, "analyticsEnabled" boolean NOT NULL, "showPoweredBy" boolean NOT NULL, "auditLogEnabled" boolean NOT NULL, "embeddingEnabled" boolean NOT NULL, "agentsEnabled" boolean NOT NULL, "aiProvidersEnabled" boolean NOT NULL DEFAULT false, "chatEnabled" boolean NOT NULL, "workerGroupsEnabled" boolean NOT NULL DEFAULT false, "managePiecesEnabled" boolean NOT NULL, "manageTemplatesEnabled" boolean NOT NULL, "customAppearanceEnabled" boolean NOT NULL, "teamProjectsLimit" character varying NOT NULL, "projectRolesEnabled" boolean NOT NULL, "globalConnectionsEnabled" boolean NOT NULL, "customRolesEnabled" boolean NOT NULL, "apiKeysEnabled" boolean NOT NULL, "ssoEnabled" boolean NOT NULL, "scimEnabled" boolean NOT NULL, "licenseKey" character varying, "stripeCustomerId" character varying, "stripeSubscriptionId" character varying, "stripeSubscriptionStatus" character varying, "projectsLimit" integer, "tablesEnabled" boolean NOT NULL, "activeFlowsLimit" integer, "eventStreamingEnabled" boolean NOT NULL, "secretManagersEnabled" boolean NOT NULL, "dedicatedWorkers" jsonb, "canary" boolean NOT NULL DEFAULT false, "customDomainsEnabled" boolean NOT NULL, "workerGroupId" character varying, CONSTRAINT "PK_d08fdd63b2b6e31d68b0134977f" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE UNIQUE INDEX "idx_platform_plan_platform_id" ON "platform_plan" ("platformId") ')
        await queryRunner.query('CREATE INDEX "idx_platform_plan_worker_group_id" ON "platform_plan" ("workerGroupId") ')
        await queryRunner.query('CREATE TABLE "event_destination" ("id" character varying(21) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platformId" character varying(21) NOT NULL, "projectId" character varying(21), "scope" character varying NOT NULL, "events" character varying array NOT NULL, "url" character varying NOT NULL, CONSTRAINT "PK_e0fe710f7b5b768b59270f7ac05" PRIMARY KEY ("id"))')
        await queryRunner.query('CREATE INDEX "idx_event_destination_platform_scope" ON "event_destination" ("platformId") WHERE scope = \'PLATFORM\'')
        await queryRunner.query('CREATE INDEX "idx_event_destination_project_scope" ON "event_destination" ("projectId") WHERE scope = \'PROJECT\'')
        await queryRunner.query('ALTER TABLE "execution" ADD CONSTRAINT "fk_execution_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "execution" ADD CONSTRAINT "fk_execution_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "execution" ADD CONSTRAINT "fk_execution_user_id" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "tool_call" ADD CONSTRAINT "fk_tool_call_execution_id" FOREIGN KEY ("executionId") REFERENCES "execution"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "tool_call" ADD CONSTRAINT "fk_tool_call_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "trigger_binding" ADD CONSTRAINT "fk_trigger_binding_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "trigger_binding" ADD CONSTRAINT "fk_trigger_binding_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "trigger_binding" ADD CONSTRAINT "fk_trigger_binding_connection_id" FOREIGN KEY ("connectionId") REFERENCES "app_connection"("id") ON DELETE SET NULL ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "scheduled_task" ADD CONSTRAINT "fk_scheduled_task_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "scheduled_task" ADD CONSTRAINT "fk_scheduled_task_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "file" ADD CONSTRAINT "fk_file_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "project" ADD CONSTRAINT "fk_project_owner_id" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "project" ADD CONSTRAINT "fk_project_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE RESTRICT ON UPDATE RESTRICT')
        await queryRunner.query('ALTER TABLE "project" ADD CONSTRAINT "fk_project_pool_id" FOREIGN KEY ("poolId") REFERENCES "concurrency_pool"("id") ON DELETE SET NULL ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "user" ADD CONSTRAINT "FK_dea97e26c765a4cdb575957a146" FOREIGN KEY ("identityId") REFERENCES "user_identity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "app_connection" ADD CONSTRAINT "fk_app_connection_owner_id" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "integration_metadata" ADD CONSTRAINT "fk_piece_metadata_file" FOREIGN KEY ("archiveId") REFERENCES "file"("id") ON DELETE RESTRICT ON UPDATE RESTRICT')
        await queryRunner.query('ALTER TABLE "platform" ADD CONSTRAINT "fk_platform_user" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT')
        await queryRunner.query('ALTER TABLE "secret_manager_connection" ADD CONSTRAINT "fk_secret_manager_connection_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "tag" ADD CONSTRAINT "FK_9dec09e187398715b7f1e32a6cb" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "piece_tag" ADD CONSTRAINT "FK_6ee5c7cca2b33700e400ea2703e" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "piece_tag" ADD CONSTRAINT "FK_5f483919deb37416ff32594918a" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "user_invitation" ADD CONSTRAINT "fk_user_invitation_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "user_invitation" ADD CONSTRAINT "fk_user_invitation_project_role_id" FOREIGN KEY ("projectRoleId") REFERENCES "project_role"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "ai_provider" ADD CONSTRAINT "fk_ai_provider_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "ai_tool_config" ADD CONSTRAINT "fk_ai_tool_config_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "table" ADD CONSTRAINT "fk_table_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "field" ADD CONSTRAINT "fk_field_table_id" FOREIGN KEY ("tableId") REFERENCES "table"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "field" ADD CONSTRAINT "fk_field_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "record" ADD CONSTRAINT "fk_record_table_id" FOREIGN KEY ("tableId") REFERENCES "table"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "record" ADD CONSTRAINT "fk_record_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "cell" ADD CONSTRAINT "fk_cell_record_id" FOREIGN KEY ("recordId") REFERENCES "record"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "cell" ADD CONSTRAINT "fk_cell_field_id" FOREIGN KEY ("fieldId") REFERENCES "field"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "cell" ADD CONSTRAINT "fk_cell_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "mcp_server" ADD CONSTRAINT "fk_mcp_server_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "mcp_server" ADD CONSTRAINT "FK_dd85c7c51f3c8137aecb1cafd34" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "connect_session" ADD CONSTRAINT "fk_connect_session_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "connect_api_key" ADD CONSTRAINT "fk_connect_api_key_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "connect_api_key" ADD CONSTRAINT "fk_connect_api_key_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "connect_oauth_app" ADD CONSTRAINT "fk_connect_oauth_app_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "project_member" ADD CONSTRAINT "fk_project_member_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "project_member" ADD CONSTRAINT "fk_project_member_user_id" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "project_member" ADD CONSTRAINT "fk_project_member_project_role_id" FOREIGN KEY ("projectRoleId") REFERENCES "project_role"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "project_plan" ADD CONSTRAINT "fk_project_plan_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "signing_key" ADD CONSTRAINT "fk_signing_key_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE RESTRICT ON UPDATE RESTRICT')
        await queryRunner.query('ALTER TABLE "oauth_app" ADD CONSTRAINT "fk_oauth_app_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "otp" ADD CONSTRAINT "fk_otp_identity_id" FOREIGN KEY ("identityId") REFERENCES "user_identity"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "api_key" ADD CONSTRAINT "fk_api_key_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "audit_event" ADD CONSTRAINT "FK_8188cdbf5c16c58d431efddd451" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "platform_analytics_report" ADD CONSTRAINT "fk_platform_analytics_report_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "embed_subdomain" ADD CONSTRAINT "fk_embed_subdomain_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "connection_key" ADD CONSTRAINT "FK_03177dc6779e6e147866d43c050" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "app_credential" ADD CONSTRAINT "FK_d82bfb4c7432a69dc2419083a0e" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "platform_plan" ADD CONSTRAINT "fk_platform_plan_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "event_destination" ADD CONSTRAINT "fk_event_destination_platform_id" FOREIGN KEY ("platformId") REFERENCES "platform"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
        await queryRunner.query('ALTER TABLE "event_destination" ADD CONSTRAINT "fk_event_destination_project_id" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION')
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('ALTER TABLE "event_destination" DROP CONSTRAINT "fk_event_destination_project_id"')
        await queryRunner.query('ALTER TABLE "event_destination" DROP CONSTRAINT "fk_event_destination_platform_id"')
        await queryRunner.query('ALTER TABLE "platform_plan" DROP CONSTRAINT "fk_platform_plan_platform_id"')
        await queryRunner.query('ALTER TABLE "app_credential" DROP CONSTRAINT "FK_d82bfb4c7432a69dc2419083a0e"')
        await queryRunner.query('ALTER TABLE "connection_key" DROP CONSTRAINT "FK_03177dc6779e6e147866d43c050"')
        await queryRunner.query('ALTER TABLE "embed_subdomain" DROP CONSTRAINT "fk_embed_subdomain_platform_id"')
        await queryRunner.query('ALTER TABLE "platform_analytics_report" DROP CONSTRAINT "fk_platform_analytics_report_platform_id"')
        await queryRunner.query('ALTER TABLE "audit_event" DROP CONSTRAINT "FK_8188cdbf5c16c58d431efddd451"')
        await queryRunner.query('ALTER TABLE "api_key" DROP CONSTRAINT "fk_api_key_platform_id"')
        await queryRunner.query('ALTER TABLE "otp" DROP CONSTRAINT "fk_otp_identity_id"')
        await queryRunner.query('ALTER TABLE "oauth_app" DROP CONSTRAINT "fk_oauth_app_platform_id"')
        await queryRunner.query('ALTER TABLE "signing_key" DROP CONSTRAINT "fk_signing_key_platform_id"')
        await queryRunner.query('ALTER TABLE "project_plan" DROP CONSTRAINT "fk_project_plan_project_id"')
        await queryRunner.query('ALTER TABLE "project_member" DROP CONSTRAINT "fk_project_member_project_role_id"')
        await queryRunner.query('ALTER TABLE "project_member" DROP CONSTRAINT "fk_project_member_user_id"')
        await queryRunner.query('ALTER TABLE "project_member" DROP CONSTRAINT "fk_project_member_project_id"')
        await queryRunner.query('ALTER TABLE "connect_oauth_app" DROP CONSTRAINT "fk_connect_oauth_app_platform_id"')
        await queryRunner.query('ALTER TABLE "connect_api_key" DROP CONSTRAINT "fk_connect_api_key_project_id"')
        await queryRunner.query('ALTER TABLE "connect_api_key" DROP CONSTRAINT "fk_connect_api_key_platform_id"')
        await queryRunner.query('ALTER TABLE "connect_session" DROP CONSTRAINT "fk_connect_session_project_id"')
        await queryRunner.query('ALTER TABLE "mcp_server" DROP CONSTRAINT "FK_dd85c7c51f3c8137aecb1cafd34"')
        await queryRunner.query('ALTER TABLE "mcp_server" DROP CONSTRAINT "fk_mcp_server_platform_id"')
        await queryRunner.query('ALTER TABLE "cell" DROP CONSTRAINT "fk_cell_project_id"')
        await queryRunner.query('ALTER TABLE "cell" DROP CONSTRAINT "fk_cell_field_id"')
        await queryRunner.query('ALTER TABLE "cell" DROP CONSTRAINT "fk_cell_record_id"')
        await queryRunner.query('ALTER TABLE "record" DROP CONSTRAINT "fk_record_project_id"')
        await queryRunner.query('ALTER TABLE "record" DROP CONSTRAINT "fk_record_table_id"')
        await queryRunner.query('ALTER TABLE "field" DROP CONSTRAINT "fk_field_project_id"')
        await queryRunner.query('ALTER TABLE "field" DROP CONSTRAINT "fk_field_table_id"')
        await queryRunner.query('ALTER TABLE "table" DROP CONSTRAINT "fk_table_project_id"')
        await queryRunner.query('ALTER TABLE "ai_tool_config" DROP CONSTRAINT "fk_ai_tool_config_platform_id"')
        await queryRunner.query('ALTER TABLE "ai_provider" DROP CONSTRAINT "fk_ai_provider_platform_id"')
        await queryRunner.query('ALTER TABLE "user_invitation" DROP CONSTRAINT "fk_user_invitation_project_role_id"')
        await queryRunner.query('ALTER TABLE "user_invitation" DROP CONSTRAINT "fk_user_invitation_project_id"')
        await queryRunner.query('ALTER TABLE "piece_tag" DROP CONSTRAINT "FK_5f483919deb37416ff32594918a"')
        await queryRunner.query('ALTER TABLE "piece_tag" DROP CONSTRAINT "FK_6ee5c7cca2b33700e400ea2703e"')
        await queryRunner.query('ALTER TABLE "tag" DROP CONSTRAINT "FK_9dec09e187398715b7f1e32a6cb"')
        await queryRunner.query('ALTER TABLE "secret_manager_connection" DROP CONSTRAINT "fk_secret_manager_connection_platform_id"')
        await queryRunner.query('ALTER TABLE "platform" DROP CONSTRAINT "fk_platform_user"')
        await queryRunner.query('ALTER TABLE "integration_metadata" DROP CONSTRAINT "fk_piece_metadata_file"')
        await queryRunner.query('ALTER TABLE "app_connection" DROP CONSTRAINT "fk_app_connection_owner_id"')
        await queryRunner.query('ALTER TABLE "user" DROP CONSTRAINT "FK_dea97e26c765a4cdb575957a146"')
        await queryRunner.query('ALTER TABLE "project" DROP CONSTRAINT "fk_project_pool_id"')
        await queryRunner.query('ALTER TABLE "project" DROP CONSTRAINT "fk_project_platform_id"')
        await queryRunner.query('ALTER TABLE "project" DROP CONSTRAINT "fk_project_owner_id"')
        await queryRunner.query('ALTER TABLE "file" DROP CONSTRAINT "fk_file_project_id"')
        await queryRunner.query('ALTER TABLE "scheduled_task" DROP CONSTRAINT "fk_scheduled_task_platform_id"')
        await queryRunner.query('ALTER TABLE "scheduled_task" DROP CONSTRAINT "fk_scheduled_task_project_id"')
        await queryRunner.query('ALTER TABLE "trigger_binding" DROP CONSTRAINT "fk_trigger_binding_connection_id"')
        await queryRunner.query('ALTER TABLE "trigger_binding" DROP CONSTRAINT "fk_trigger_binding_platform_id"')
        await queryRunner.query('ALTER TABLE "trigger_binding" DROP CONSTRAINT "fk_trigger_binding_project_id"')
        await queryRunner.query('ALTER TABLE "tool_call" DROP CONSTRAINT "fk_tool_call_project_id"')
        await queryRunner.query('ALTER TABLE "tool_call" DROP CONSTRAINT "fk_tool_call_execution_id"')
        await queryRunner.query('ALTER TABLE "execution" DROP CONSTRAINT "fk_execution_user_id"')
        await queryRunner.query('ALTER TABLE "execution" DROP CONSTRAINT "fk_execution_platform_id"')
        await queryRunner.query('ALTER TABLE "execution" DROP CONSTRAINT "fk_execution_project_id"')
        await queryRunner.query('DROP INDEX "public"."idx_event_destination_project_scope"')
        await queryRunner.query('DROP INDEX "public"."idx_event_destination_platform_scope"')
        await queryRunner.query('DROP TABLE "event_destination"')
        await queryRunner.query('DROP INDEX "public"."idx_platform_plan_worker_group_id"')
        await queryRunner.query('DROP INDEX "public"."idx_platform_plan_platform_id"')
        await queryRunner.query('DROP TABLE "platform_plan"')
        await queryRunner.query('DROP TABLE "app_credential"')
        await queryRunner.query('DROP INDEX "public"."idx_connection_key_project_id"')
        await queryRunner.query('DROP TABLE "connection_key"')
        await queryRunner.query('DROP TABLE "appsumo"')
        await queryRunner.query('DROP INDEX "public"."idx_embed_subdomain_hostname"')
        await queryRunner.query('DROP INDEX "public"."idx_embed_subdomain_platform_id"')
        await queryRunner.query('DROP TABLE "embed_subdomain"')
        await queryRunner.query('DROP INDEX "public"."idx_platform_analytics_report_platform_id"')
        await queryRunner.query('DROP TABLE "platform_analytics_report"')
        await queryRunner.query('DROP INDEX "public"."audit_event_platform_id_action_idx"')
        await queryRunner.query('DROP INDEX "public"."audit_event_platform_id_user_id_action_idx"')
        await queryRunner.query('DROP INDEX "public"."audit_event_platform_id_project_id_user_id_action_idx"')
        await queryRunner.query('DROP TABLE "audit_event"')
        await queryRunner.query('DROP TABLE "api_key"')
        await queryRunner.query('DROP INDEX "public"."idx_otp_identity_id_type"')
        await queryRunner.query('DROP TABLE "otp"')
        await queryRunner.query('DROP INDEX "public"."idx_oauth_app_platformId_pieceName"')
        await queryRunner.query('DROP TABLE "oauth_app"')
        await queryRunner.query('DROP TABLE "signing_key"')
        await queryRunner.query('DROP INDEX "public"."idx_plan_project_id"')
        await queryRunner.query('DROP TABLE "project_plan"')
        await queryRunner.query('DROP INDEX "public"."idx_project_member_project_id_user_id_platform_id"')
        await queryRunner.query('DROP TABLE "project_member"')
        await queryRunner.query('DROP INDEX "public"."idx_concurrency_pool_platform_key"')
        await queryRunner.query('DROP TABLE "concurrency_pool"')
        await queryRunner.query('DROP INDEX "public"."idx_connect_oauth_app_platform_id_piece_name"')
        await queryRunner.query('DROP TABLE "connect_oauth_app"')
        await queryRunner.query('DROP INDEX "public"."idx_connect_api_key_project_id"')
        await queryRunner.query('DROP TABLE "connect_api_key"')
        await queryRunner.query('DROP INDEX "public"."idx_connect_session_hashed_token"')
        await queryRunner.query('DROP INDEX "public"."idx_connect_session_project_id_external_user_id"')
        await queryRunner.query('DROP TABLE "connect_session"')
        await queryRunner.query('DROP TABLE IF EXISTS "tool_search_index"')
        await queryRunner.query('DROP INDEX "public"."idx_mcp_oauth_token_refresh"')
        await queryRunner.query('DROP TABLE "mcp_oauth_token"')
        await queryRunner.query('DROP INDEX "public"."idx_mcp_oauth_code"')
        await queryRunner.query('DROP TABLE "mcp_oauth_authorization_code"')
        await queryRunner.query('DROP INDEX "public"."idx_mcp_oauth_client_client_id"')
        await queryRunner.query('DROP TABLE "mcp_oauth_client"')
        await queryRunner.query('DROP INDEX "public"."idx_mcp_server_platform_id"')
        await queryRunner.query('DROP INDEX "public"."idx_mcp_server_token"')
        await queryRunner.query('DROP INDEX "public"."mcp_server_project_id"')
        await queryRunner.query('DROP TABLE "mcp_server"')
        await queryRunner.query('DROP INDEX "public"."idx_user_identity_email"')
        await queryRunner.query('DROP TABLE "user_identity"')
        await queryRunner.query('DROP INDEX "public"."idx_cell_project_id_field_id_record_id_unique"')
        await queryRunner.query('DROP TABLE "cell"')
        await queryRunner.query('DROP INDEX "public"."idx_record_table_id_project_id_record_id"')
        await queryRunner.query('DROP INDEX "public"."idx_record_project_id_table_id"')
        await queryRunner.query('DROP TABLE "record"')
        await queryRunner.query('DROP INDEX "public"."idx_field_project_id_table_id_name"')
        await queryRunner.query('DROP TABLE "field"')
        await queryRunner.query('DROP INDEX "public"."idx_table_folder_id"')
        await queryRunner.query('DROP INDEX "public"."idx_table_project_id_name"')
        await queryRunner.query('DROP TABLE "table"')
        await queryRunner.query('DROP TABLE "project_role"')
        await queryRunner.query('DROP INDEX "public"."idx_ai_tool_config_platform_capability"')
        await queryRunner.query('DROP TABLE "ai_tool_config"')
        await queryRunner.query('DROP INDEX "public"."idx_ai_provider_platform_id_provider"')
        await queryRunner.query('DROP TABLE "ai_provider"')
        await queryRunner.query('DROP INDEX "public"."idx_user_invitation_email_platform_project"')
        await queryRunner.query('DROP TABLE "user_invitation"')
        await queryRunner.query('DROP INDEX "public"."tag_platformId"')
        await queryRunner.query('DROP TABLE "piece_tag"')
        await queryRunner.query('DROP TABLE "tag"')
        await queryRunner.query('DROP INDEX "public"."idx_secret_manager_connection_platform_id"')
        await queryRunner.query('DROP TABLE "secret_manager_connection"')
        await queryRunner.query('DROP INDEX "public"."idx_platform_sso_domain"')
        await queryRunner.query('DROP TABLE "platform"')
        await queryRunner.query('DROP INDEX "public"."idx_piece_metadata_name_platform_id_version"')
        await queryRunner.query('DROP TABLE "integration_metadata"')
        await queryRunner.query('DROP INDEX "public"."idx_app_connection_owner_id"')
        await queryRunner.query('DROP INDEX "public"."idx_app_connection_platform_id_and_external_id"')
        await queryRunner.query('DROP TABLE "app_connection"')
        await queryRunner.query('DROP INDEX "public"."idx_user_identity_id"')
        await queryRunner.query('DROP INDEX "public"."idx_user_platform_id_external_id"')
        await queryRunner.query('DROP INDEX "public"."idx_user_platform_id_email"')
        await queryRunner.query('DROP TABLE "user"')
        await queryRunner.query('DROP TABLE "store-entry"')
        await queryRunner.query('DROP INDEX "public"."idx_project_worker_group"')
        await queryRunner.query('DROP INDEX "public"."idx_project_pool_id"')
        await queryRunner.query('DROP INDEX "public"."idx_project_platform_id"')
        await queryRunner.query('DROP INDEX "public"."idx_project_platform_id_external_id"')
        await queryRunner.query('DROP INDEX "public"."idx_project_owner_id"')
        await queryRunner.query('DROP TABLE "project"')
        await queryRunner.query('DROP TABLE "flag"')
        await queryRunner.query('DROP INDEX "public"."idx_file_type_created_desc"')
        await queryRunner.query('DROP INDEX "public"."idx_file_project_id"')
        await queryRunner.query('DROP TABLE "file"')
        await queryRunner.query('DROP INDEX "public"."idx_scheduled_task_platform_id"')
        await queryRunner.query('DROP INDEX "public"."idx_scheduled_task_project_id"')
        await queryRunner.query('DROP TABLE "scheduled_task"')
        await queryRunner.query('DROP INDEX "public"."idx_trigger_binding_piece_trigger"')
        await queryRunner.query('DROP INDEX "public"."idx_trigger_binding_connection_id"')
        await queryRunner.query('DROP INDEX "public"."idx_trigger_binding_platform_id"')
        await queryRunner.query('DROP INDEX "public"."idx_trigger_binding_project_id"')
        await queryRunner.query('DROP TABLE "trigger_binding"')
        await queryRunner.query('DROP INDEX "public"."idx_tool_call_created"')
        await queryRunner.query('DROP INDEX "public"."idx_tool_call_project_id"')
        await queryRunner.query('DROP INDEX "public"."idx_tool_call_execution_id"')
        await queryRunner.query('DROP TABLE "tool_call"')
        await queryRunner.query('DROP INDEX "public"."idx_execution_created"')
        await queryRunner.query('DROP INDEX "public"."idx_execution_status"')
        await queryRunner.query('DROP INDEX "public"."idx_execution_platform_id"')
        await queryRunner.query('DROP INDEX "public"."idx_execution_project_id"')
        await queryRunner.query('DROP TABLE "execution"')
        if (databaseType !== DatabaseType.PGLITE) {
            await queryRunner.query('DROP COLLATION en_natural')
        }
    }

}
