export const formErrors = {
    required: 'required',
    invalidGitRepoSlug: 'invalidGitRepoSlug',
    invalidGitRepoBranch: 'invalidGitRepoBranch',
    invalidGitRepoRemoteUrl: 'invalidGitRepoRemoteUrl',
    invalidExternalId: 'invalidExternalId',
    invalidFileName: 'invalidFileName',
    messageRequiresContentOrFiles: 'messageRequiresContentOrFiles',
    apiKeyExpiryMustBeFuture: 'apiKeyExpiryMustBeFuture',
    activeFlowsLimitMin: 'activeFlowsLimitMin',
    activeFlowsLimitMax: 'activeFlowsLimitMax',
    invalidHexColor: 'invalidHexColor',
    invalidCustomTabName: 'invalidCustomTabName',
    selectAtLeastOneProject: 'selectAtLeastOneProject',
    archivePayloadTooLarge: 'archivePayloadTooLarge',
    firstValueRequired: 'firstValueRequired',
    secondValueRequired: 'secondValueRequired',
    operatorRequired: 'operatorRequired',
    invalidOAuthRedirectScheme: 'invalidOAuthRedirectScheme',
} as const
